blank_issues_enabled: false
contact_links:
  - name: Questions and support
    url: https://github.com/devmoreir4/godot-3d-multiplayer-template/discussions
    about: Ask questions and get help using the template.
